### ISSUE TITLE
DNS Resolution Failure Without Plaintext Fallback

### ISSUE THREAD

**Issue by starraiderx** [HotCakeX/WinSecureDNSMgr#2]
Hello,

I'm encountering an issue with WinSecureDNSMgr on my Windows machine. The problem arises with DNS resolution: it ceases to function unless I enable the fallback to plaintext in my Windows adapter settings.

I'm using AdGuard Home as my DNS server for DNS over HTTPS (DoH). Notably, my AdGuard Home installation utilizes a certificate created with makecert. This setup appears to be functioning correctly, as I can use DoH in Firefox with the maximum protection settings (no fallback) without any problems.

The DNS server is set up on a local address (192.168.XXX.XXX). Furthermore, I have blocked all other DoH servers in my network using BanIP, although I don't believe this is contributing to the issue with WinSecureDNSMgr.

The Command I am using: `Set-CDOH -DoHTemplate https://192.168.XXX.XXX/dns-query -IPV4s 192.168.XXX.XXX`

**Comment by HotCakeX** [comment]
Hi,
Does your config work when you manually enter them in Windows network adapter settings?

**Comment by starraiderx** [comment]
No

**Comment by starraiderx** [comment]
```
Get-DnsClientDohServerAddress

ServerAddress        AllowFallbackToUdp AutoUpgrade DohTemplate
-------------        ------------------ ----------- -----------
149.112.112.112      False              False       https://dns.quad9.net/dns-query
9.9.9.9              False              False       https://dns.quad9.net/dns-query
8.8.8.8              False              False       https://dns.google/dns-query
8.8.4.4              False              False       https://dns.google/dns-query
192.168.XXX.XXX          False              True        https://192.168.XXX.XXX/dns-query
1.1.1.1              False              False       https://cloudflare-dns.com/dns-query
1.0.0.1              False              False       https://cloudflare-dns.com/dns-query
2001:4860:4860::8844 False              False       https://dns.google/dns-query
2001:4860:4860::8888 False              False       https://dns.google/dns-query
2606:4700:4700::1001 False              False       https://cloudflare-dns.com/dns-query
2606:4700:4700::1111 False              False       https://cloudflare-dns.com/dns-query
2620:fe::9           False              False       https://dns.quad9.net/dns-query
2620:fe::fe          False              False       https://dns.quad9.net/dns-query
```

In the current setup of my router, it's configured to block my PC from accessing any of the specified IP addresses, except for the local IP.

Everything else in the configuration seems correct. This is the reason why enabling the fallback option for plaintext communication allows for successful connectivity.

**Comment by starraiderx** [comment]
Hey, is there any way to completely revert this module? I noticed its also causing problems with my VPN.

**Comment by HotCakeX** [comment]
I'm planning on reworking the entire module soon, it's many  months since I last touched its code because it's been just working fine for me, but I realize now there are more use cases I have to consider and implement.

To revert things it does, first run this in an elevated PowerShell

```powershell
 Remove-Item -Path 'HKLM:System\CurrentControlSet\Services\Dnscache\InterfaceSpecificParameters\*' -Recurse
```

It will remove the DoH settings for all network Interfaces. It's harmless.

Then run this command

```powershell
Get-DnsClientDohServerAddress
```

It will show you all of the saved DoH settings on your system.

Documentation: https://learn.microsoft.com/en-us/powershell/module/dnsclient/get-dnsclientdohserveraddress

Then use this cmdlet: `Remove-DnsClientDohServerAddress`, documentation: https://learn.microsoft.com/en-us/powershell/module/dnsclient/remove-dnsclientdohserveraddress

It will let you remove any saved DoH configuration from your system.

There are examples in each document too. Let me know if you need more help with them and sorry for the manual work.

**Comment by HotCakeX** [comment]
@starraiderx I just released a new update with a huge list of changes, please try it and let me know how it works for you

https://github.com/HotCakeX/WinSecureDNSMgr/releases/tag/v0.0.5

The module doesn't have auto-updating system yet like my other modules so you'll have to update it manually:

https://github.com/HotCakeX/WinSecureDNSMgr?tab=readme-ov-file#installation

It also has reset feature so you don't have to manually do anything anymore

If that's okay I'm closing this issue because a lot has changed since it was opened, if you find a new bug please open a new issue with as much details as possible so i can fix it asap. thank you ^^
